export const loanPackages = [
  {
    id: 1,
    range: "500 - 1500 Ksh",
    interestRate10Days: "12%",
    interestRate14Days: "16%",
    repaymentSchedule: "Daily",
    finePercentage: "5% of borrowed amount",
    incrementalFines: "2% per missed payment",
    processingFee: "50 Ksh",
  },
  {
    id: 2,
    range: "1501 - 3000 Ksh",
    interestRate10Days: "10%",
    interestRate14Days: "14%",
    repaymentSchedule: "Weekly",
    finePercentage: "4% of borrowed amount",
    incrementalFines: "1.5% per missed payment",
    processingFee: "75 Ksh",
  },
  {
    id: 3,
    range: "3001 - 5000 Ksh",
    interestRate10Days: "9%",
    interestRate14Days: "13%",
    repaymentSchedule: "Bi-Weekly",
    finePercentage: "6% of borrowed amount",
    incrementalFines: "2.5% per missed payment",
    processingFee: "100 Ksh",
  },
  {
    id: 4,
    range: "5001 - 7500 Ksh",
    interestRate10Days: "8%",
    interestRate14Days: "12%",
    repaymentSchedule: "Monthly",
    finePercentage: "7% of borrowed amount",
    incrementalFines: "3% per missed payment",
    processingFee: "150 Ksh",
  },
  {
    id: 5,
    range: "7501 - 10000 Ksh",
    interestRate10Days: "7%",
    interestRate14Days: "11%",
    repaymentSchedule: "Monthly",
    finePercentage: "8% of borrowed amount",
    incrementalFines: "3.5% per missed payment",
    processingFee: "200 Ksh",
  },
  {
    id: 6,
    range: "10001 - 15000 Ksh",
    interestRate10Days: "6%",
    interestRate14Days: "10%",
    repaymentSchedule: "Monthly",
    finePercentage: "9% of borrowed amount",
    incrementalFines: "4% per missed payment",
    processingFee: "250 Ksh",
  },
];
